tap "homebrew/bundle"
tap "homebrew/cask-fonts"
tap "microsoft/git" # git-credential-manager-core
tap "olets/tap" # zsh-abbr
tap "romkatv/powerlevel10k"

brew "asdf"
brew "bat"
brew "coreutils"
brew "fzf"
brew "git"
brew "git-delta"
brew "gnupg"
brew "graphviz" # for PlantUML
brew "jq"
brew "mas"
brew "pinentry-mac"
brew "powerlevel10k"
brew "tldr"
brew "zoxide"
brew "zsh"
brew "zsh-abbr"
brew "zsh-autosuggestions"
brew "zsh-syntax-highlighting"

cask "boop"
cask "calibre"
cask "docker"
cask "git-credential-manager-core"
cask "google-chrome"
cask "iterm2"
cask "jetbrains-toolbox"
cask "keepassxc"
cask "microsoft-auto-update"
cask "microsoft-office"
cask "obsidian"
cask "slack"
cask "visual-studio-code"
cask "yubico-authenticator"

# Fonts
cask "font-meslo-lg-nerd-font"

# App Store
mas "Magnet", id: 441258766