tap "homebrew/bundle"
tap "homebrew/cask"
tap "homebrew/cask-fonts"
tap "homebrew/core"
tap "olets/tap" # zsh-abbr
tap "romkatv/powerlevel10k"

brew "asdf"
brew "bat"
brew "coreutils"
brew "fzf"
brew "git"
brew "git-delta"
brew "gnupg"
brew "pinentry-mac"
brew "powerlevel10k"
brew "zoxide"
brew "zsh"
brew "zsh-abbr"
brew "zsh-autosuggestions"
brew "zsh-syntax-highlighting"

cask "google-chrome"
cask "iterm2"
cask "obsidian"
cask "visual-studio-code"

# Fonts
cask "font-meslo-lg-nerd-font"
