# Get editor completions based on the config schema
"$schema" = 'https://starship.rs/config-schema.json'

# Inserts a blank line between shell prompts
add_newline = true

[character]
success_symbol = '[➜](bold green)'
error_symbol = '[✗](bold red)'

[cmd_duration]
min_time = 1000
format = '⧖ took [$duration]($style)'
style = 'bold'

[directory]
truncation_length = 5
truncate_to_repo = false
truncation_symbol = '…/'

[git_status]
ahead = '⇡${count}'
behind = '⇣${count}'
conflicted = '⚡'
diverged = '⇕⇡${ahead_count}⇣${behind_count}'
stashed = ''

# Disable the package module, hiding it from the prompt completely
[package]
disabled = true

[terraform]
format = "via [$symbol$version \\[$workspace\\]]($style) "
